{% set name = "coreutils" %}
{% set version = "9.2" %}
{% set sha256 = "6885ff47b9cdb211de47d368c17853f406daaf98b148aaecdf10de29cc04b0b3" %}

package:
  name: coreutils-split
  version: {{ version }}

source:
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

outputs:
  - name: {{ name }}
    script: build_coreutils.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - make

    test:
      commands:
        - ln --relative --help
        - wc --version
        - cat --version

  - name: gnu-{{ name }}
    script: build_gnu-coreutils.sh


    requirements:
      build:
        - {{ compiler('c') }}
        - make

    test:
      commands:
        - gln --relative --help
        # to confirm gln vs ln
        - ln --version  # [linux64]
        - gln --version  # [linux64]
        - gwc --version
        - gcat --version

about:
  home: https://www.gnu.org/software/coreutils
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: The GNU Core Utilities are the basic file, shell and text manipulation utilities of the GNU operating system.

  doc_url: https://www.gnu.org/software/coreutils/manual/html_node/index.html
  dev_url: http://git.savannah.gnu.org/cgit/coreutils.git

extra:
  recipe-maintainers:
    - ngam
    - sodre
    - mbargull
  feedstock-name: coreutils
